name: absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  convex_bottom_bar: ^3.2.0
  dropdown_search: ^5.0.6
  firebase_auth: ^4.6.1
  firebase_core: 2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: 4.6.5
  image_picker: ^0.8.7+5
  intl: 0.18.1
  lottie: ^2.3.2
  syncfusion_flutter_datepicker: ^22.1.34

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - gambar/
    - lottie/
  uses-material-design: true
