// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP3q1ocEEq9xgNcejUWHlQWuRlvLrp7FU',
    appId: '1:705646335421:web:e94828e38f963db0516ed4',
    messagingSenderId: '705646335421',
    projectId: 'absensi-94cbe',
    authDomain: 'absensi-94cbe.firebaseapp.com',
    storageBucket: 'absensi-94cbe.appspot.com',
    measurementId: 'G-G57DDF4SQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14NkiBwx0WhqvizoP8rSDnQzM2mND_JE',
    appId: '1:705646335421:android:c2ac1d2fe0defd41516ed4',
    messagingSenderId: '705646335421',
    projectId: 'absensi-94cbe',
    storageBucket: 'absensi-94cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3b5AwwNYzNTMkuAO4skgh0lmcg2lUMlI',
    appId: '1:705646335421:ios:7392b67e967ed1d9516ed4',
    messagingSenderId: '705646335421',
    projectId: 'absensi-94cbe',
    storageBucket: 'absensi-94cbe.appspot.com',
    iosBundleId: 'com.azhar.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3b5AwwNYzNTMkuAO4skgh0lmcg2lUMlI',
    appId: '1:705646335421:ios:372ce101c23f7987516ed4',
    messagingSenderId: '705646335421',
    projectId: 'absensi-94cbe',
    storageBucket: 'absensi-94cbe.appspot.com',
    iosBundleId: 'com.azhar.absensi.RunnerTests',
  );
}
